<h1>Basic python</h1>


<h2>1. Split this string</h2>

In [3]:
s = "Hi there Sam!"
s_list = s.split(" ")
for i in s_list:
  print(i)

Hi
there
Sam!


<h1>2. Use .format() to print the following string.</h1>

<h2>Output should be: The diameter of Earth is 12742 kilometers.</h2>

In [ ]:
planet = "Earth"
diameter = 12742

In [12]:
result = "The diameter of {Name} is {Value} kilometers". format(Name = planet, Value = diameter)
print(result)

The diameter of Earth is 12742 kilometers


<h1>3. In this nest dictionary grab the word "hello"</h1>

In [15]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [16]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


<h1>Numpy</h1>

<h2> 4.1 Create an array of 10 zeros?</h2>


<h2>4.2 Create an array of 10 fives?</h2> 

In [21]:
import numpy as np
arr1 = np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
arr2 = np.ones(10)*5
print(arr2)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


<h1>5. Create an array of all the even integers from 20 to 35</h1>

In [23]:
arr3 = np.arange(20,35,2)
print(arr3)

[20 22 24 26 28 30 32 34]


<h1>6. Create a 3x3 matrix with values ranging from 0 to 8</h1>

In [25]:
arr4 = np.arange(0,9).reshape(3,3)
print(arr4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<h1>7. Concatinate a and b</h1>

<h2>a = np.array([1, 2, 3]), b = np.array([4, 5, 6])</h2>

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr5 = np.concatenate((a, b))
print(arr5)

[1 2 3 4 5 6]


 <h1>Pandas</h1>

<h2>8. Create a dataframe with 3 rows and 2 columns</h2>

In [29]:
import pandas as pd
res = pd.DataFrame(np.random.randint(0,100,size=(3, 2)), columns=list('AB'))
print(res)

    A   B
0  55  27
1  27  77
2  31  57


<h1>9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023</h1>

In [30]:
import pandas as pd 
date = pd.date_range(start ='1-1-2023', end ='5-10-2023', freq ='10D')
  
for val in date:
    print(val)

2023-01-01 00:00:00
2023-01-11 00:00:00
2023-01-21 00:00:00
2023-01-31 00:00:00
2023-02-10 00:00:00
2023-02-20 00:00:00
2023-03-02 00:00:00
2023-03-12 00:00:00
2023-03-22 00:00:00
2023-04-01 00:00:00
2023-04-11 00:00:00
2023-04-21 00:00:00
2023-05-01 00:00:00


<h1>10. Create 2D list to DataFrame</h1>

In [32]:
lst = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
import pandas as pd
df = pd.DataFrame(lst, columns =['SNo.', 'Name', 'Age']) 
print(df)

   SNo. Name  Age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
